### PR TITLE
extlib: convert SDL-1.2.15 to a Git submodule

### PR DESCRIPTION
**Pull request by SeanMcG**
Additionally, this applies patches at build time for the changes we had locally before:

- do not install the manpages
- fix the function signature for XData32 on X11 (this was already applied upstream post-`1.2.15`)
- set the GNU libtool tags appropriately
- update config.{guess,sub}

### CODE REVIEW

**Comment by SeanMcG** [comment]
Draft because I think this needs some conversation.

At the very least, it's not clear how we should communicate to developers that they will need to `git clone --recursive` to populate `extlib/src/SDL-1.2.15`

**Comment by playmer** [comment]
Regarding the cloning, we probably need to set up some developer instructions. I was planning on doing that sometime next week in the CMake branch (I have a hackathon next week, so I was going to dedicate it to porting to more platforms and filling out instructions).

We can start that documentation in this PR Instructions on how to clone, and how to set up and build on Linux/Windows.

**Comment by SeanMcG** [comment]
> Draft because I think this needs some conversation.
> 
> At the very least, it's not clear how we should communicate to developers that they will need to `git clone --recursive` to populate `extlib/src/SDL-1.2.15`

Handled skillfully by @playmer in #74.
This is ready for review now.

**Comment by SeanMcG** [comment]
OK, talked with @Galladite27 on Discord and submodules is not the way we want to go for `extlib`. Closing.

**Pull request closed without merging**
