### PR TITLE
Use SDLmain on Windows, rather than maintaining our own Impl.

### PR DESCRIPTION
**Pull request by playmer**
We currently rely on a forked version of the SDLmain library on Windows, through usage of `SDL_win32_main.c`. This is primarily just so we can place the std output redirects into AppData. 

Rather than maintain this entire file, I've updated the scripts to use SDLmain itself, and then within `onscripter.cpp` disabled the SDLmain redirection and re-implemented the redirection to AppData. If we so desire it's also set up to allow us to expand redirection for platforms where it makes sense to do so. (Unix, Mac, maybe others.)

SDLmain is fairly important for the more esoteric platforms, so trying to unify on using it's entry point is what led to me looking deeper at this.

This is missing some compatability ifdefs that allowed compiling for Windows CE. I could bring them back, but I have no way to actually test that codepath.

In addition I've sorted some of our options to not use redundant platform ifdefs.

### CODE REVIEW

**Comment by Galladite27** [comment]
Is this ready to go?

**Comment by playmer** [comment]
Yup

**Comment by Galladite27** [comment]
I just have one complaint about this. I don't like how the Windows-specific flags are moved to be grouped together. I get this reduces the number of `#ifdef`s, but they are where they are for a reason - because they're related to similar OS-agnostic flags with which they're grouped. Please remove this and then I'll merge.

**Comment by playmer** [comment]
No worries, will work on it over the weekend.

**Comment by Galladite27** [comment]
Thanks

**Pull request merged**
