### PR TITLE
configure: clang as a supported compiler, OpenBSD fixes, -O3 to -O2

### PR DESCRIPTION
**Pull request by grodzio1**
I have modified the script to accept clang as a supported compiler. ONScripter-EN builds without fail using clang, this useful mostly on OpenBSD and FreeBSD. I've made it so any OS that also uses clang can be easily added in the future. I've also fixed the bzip2 check on OpenBSD, and as above I've made it so any other OS that uses different paths for bzip2 libraries and headers can be easily added to it. Lastly, I've changed the compiler optimisation flags from -O3 to -O2, as -O3 is generally not recommended.

### CODE REVIEW

**Comment by SeanMcG** [comment]
Commit history really should not have the reverts, can you squash these?

**Comment by SeanMcG** [comment]
Also, I really really really think we should convert the compiler identification to something that is actually compiled -- especially now that I have looked at the new Intel compiler suite and how both it's binary name (`icc -> icx`) and it's output for `--version` has changed since ICC.

**Comment by SeanMcG** [comment]
I'm not generally opposed to the O3 -> O2 change, but I wonder if we are maybe going to lose some of tulhe nicer optimizations at that level -- like some of the loop-unrolling stuff in `gcc` anyways. We don't really have metrics on what that does either, and I am guessing no stats on how old a machine people run ons-en with.

**Comment by grodzio1** [comment]
> Also, I really really really think we should convert the compiler identification to something that is actually compiled -- especially now that I have looked at the new Intel compiler suite and how both it's binary name (`icc -> icx`) and it's output for `--version` has changed since ICC.
What I wrote is more or less a quick fix just so it can compile under clang. I don't think it ought to be permanent. The compiler detection probably should be rewritten to work with modern versions of compilers.

> I'm not generally opposed to the O3 -> O2 change, but I wonder if we are maybe going to lose some of the nicer optimizations at that level -- like some of the loop-unrolling stuff in `gcc` anyways. We don't really have metrics on what that does either, and I am guessing no stats on how old a machine people run ons-en with.
I don't think a visual engine needs maximum performance. In this case, I think -O3 is more trouble than it's worth.

**Comment by grodzio1** [comment]
Fixed. Now there is a commit for compiler flags and the other one for clang and OpenBSD fixes. Is this ok?

**Comment by SeanMcG** [comment]
> Fixed. Now there is a commit for compiler flags and the other one for clang and OpenBSD fixes. Is this ok?

Much better, thanks.

**Review by Galladite27 — APPROVED** [review]

**Pull request merged**
